#-------------------------------
# General Site Settings

title: Sreenivasan Ramesh
description: Welcome to my personal blog. I'm Sreenivasan Ramesh - a graduate Computer Science student at ASU. 
baseurl: "" 
url: ""

#-------------------------------
# About Section
author: "Sreenivasan Ramesh"
author-name:   "Sreenivasan Ramesh"
author-avatar: img/site/avatar.jpg


#-------------------------------
# Contact links
github: https://github.com/sreenivasanramesh
linkedin: https://linkedin.com/in/sreenivasanramesh
#facebook:  https://facebook.com/ # Add your Facebook handle
twitter:   https://twitter.com/sreenivasan_ # Add your Facebook handle
#instagram: https://instagram.com/sreenivasan.ramesh # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: sreenivasanramesh-github-io # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-166234180-1

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
